# Generated by Django 2.0.3 on 2018-04-24 17:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('object_id', models.PositiveIntegerField(verbose_name='评论附加对象id')),
                ('published_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
                ('n_like', models.PositiveIntegerField(default=0, verbose_name='评论喜欢数')),
                ('n_dislike', models.PositiveIntegerField(default=0, verbose_name='评论讨厌数')),
                ('is_spam', models.BooleanField(default=False, verbose_name='是否是评论垃圾')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='评论附加对象的ct类型')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.Comment', verbose_name='父级评论')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
    ]
