# Generated by Django 2.0.3 on 2018-04-22 14:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_removed',
            field=models.BooleanField(default=False, verbose_name='是否被删除'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False, verbose_name='是否是评论垃圾'),
        ),
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='n_dislike',
            field=models.PositiveIntegerField(default=0, verbose_name='评论讨厌数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='n_like',
            field=models.PositiveIntegerField(default=0, verbose_name='评论喜欢数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.Comment', verbose_name='父级评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
