# Generated by Django 2.0.3 on 2018-04-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20180422_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_removed',
        ),
    ]
