# Generated by Django 2.0.3 on 2018-04-22 17:27

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comment.Comment', verbose_name='父级评论'),
        ),
    ]
