# Generated by Django 2.0.3 on 2018-05-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='bloguser/avatar.png', upload_to='bloguser/images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
