# Generated by Django 2.0.3 on 2018-05-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0002_auto_20180504_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(default='', max_length=100, verbose_name='用户头像url'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='bloguser/avatar.png', upload_to='bloguser/images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
