# Generated by Django 2.0.3 on 2018-07-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0004_auto_20180506_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
