# Generated by Django 2.0.3 on 2018-07-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0005_auto_20180704_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, help_text='邮箱是唯一的', max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
    ]
