# Generated by Django 2.0.3 on 2018-07-29 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0006_auto_20180704_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageAuthCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='短信验证码')),
                ('phone_num', models.CharField(max_length=14, verbose_name='接收手机号')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='手机验证码产生时间')),
                ('expiration', models.DateTimeField(verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '手机短信验证码',
                'verbose_name_plural': '手机短信验证码',
            },
        ),
    ]
