# Generated by Django 2.0.3 on 2018-07-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0007_messageauthcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageauthcode',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='过期时间'),
        ),
    ]
