# Generated by Django 2.0.3 on 2018-08-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0008_auto_20180729_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('username', 'email')},
        ),
    ]
