# Generated by Django 2.0.3 on 2018-08-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloguser', '0009_auto_20180802_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together=set(),
        ),
    ]
