# Generated by Django 2.0.3 on 2018-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20180819_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsorder',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AlterField(
            model_name='goodsorder',
            name='sign_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签收时间'),
        ),
    ]
