# Generated by Django 2.0.3 on 2018-08-02 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20180802_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsorder',
            name='order_sn',
            field=models.CharField(max_length=50, unique=True, verbose_name='订单编号'),
        ),
    ]
