# Generated by Django 2.0.3 on 2018-08-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20180819_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsorder',
            name='status',
            field=models.CharField(choices=[('complete', '已支付订单'), ('un_complete', '未支付订单'), ('cancel', '订单取消'), ('WAIT_BUYER_PAY', '交易创建，等待买家付款'), ('TRADE_CLOSED', '未付款交易超时关闭，或支付完成后全额退款'), ('TRADE_SUCCESS', '交易支付成功'), ('TRADE_FINISHED', '交易结束，不可退款')], default='WAIT_BUYER_PAY', max_length=20, verbose_name='支付状态'),
        ),
    ]
