# Generated by Django 2.0.3 on 2018-08-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20180802_0247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentlogs',
            options={'verbose_name': '商品支付记录', 'verbose_name_plural': '商品支付记录'},
        ),
        migrations.AlterField(
            model_name='goodsorder',
            name='order_amount',
            field=models.FloatField(default=0, verbose_name='订单金额'),
        ),
    ]
