# Generated by Django 2.0.3 on 2018-08-23 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20180821_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlogs',
            name='goods_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade.GoodsOrder', verbose_name='关联订单'),
        ),
    ]
