# Generated by Django 2.0.3 on 2018-08-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_signer_sign_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='n_goods',
            field=models.PositiveIntegerField(default=1, verbose_name='商品购买数量'),
        ),
    ]
