# Generated by Django 2.0.3 on 2018-05-01 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFile', models.ImageField(max_length=200, upload_to='kindeditor/images/%Y/%m', verbose_name='kindeditor上传的图片')),
            ],
        ),
    ]
