# Generated by Django 2.0.3 on 2018-03-28 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='少于50字符', max_length=50, verbose_name='博文标题'),
        ),
    ]
