# Generated by Django 2.0.3 on 2018-05-02 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='n_comments',
        ),
    ]
