# Generated by Django 2.0.3 on 2018-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin_post_from',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='原博文出处名称'),
        ),
        migrations.AlterField(
            model_name='post',
            name='origin_post_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='原博文URL链接'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url_object_id',
            field=models.CharField(blank=True, help_text='不写默认为博文url摘要', max_length=255, null=True, unique=True, verbose_name='源博文唯一标识'),
        ),
    ]
