# Generated by Django 2.0.3 on 2018-04-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发表')], default='draft', max_length=10, verbose_name='编辑状态'),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='blog/blog_cover/default.jpg', max_length=200, upload_to='blog/blog_cover/%Y/%m', verbose_name='博文封面'),
        ),
    ]
