# Generated by Django 2.0.3 on 2018-05-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180502_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resource',
            field=models.FileField(max_length=200, upload_to='blog/resources/%Y/%m/', verbose_name='资源文件'),
        ),
    ]
