# Generated by Django 2.0.3 on 2018-08-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180802_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hasbe_indexed',
            field=models.BooleanField(default=False, verbose_name='已被索引'),
        ),
    ]
