# Generated by Django 2.0.3 on 2018-06-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180628_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_url',
            field=models.URLField(blank=True, default='', help_text='不写默认为默认为封面url', null=True, verbose_name='博文封面url'),
        ),
    ]
