# Generated by Django 2.0.3 on 2018-05-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180502_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(default='', max_length=300, verbose_name='博文摘要'),
        ),
    ]
