# Generated by Django 2.0.3 on 2018-08-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_hasbe_indexed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='blog/blog_cover/default.jpg', max_length=200, upload_to='blog/blog_cover/', verbose_name='博文封面'),
        ),
    ]
