# Generated by Django 2.0.3 on 2018-07-30 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180630_2044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_post', '可以读取对应的博文实例'),), 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
    ]
