# Generated by Django 2.0.3 on 2018-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180504_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=300, verbose_name='博文摘要'),
        ),
    ]
