# Generated by Django 2.0.3 on 2018-07-31 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180730_1926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_post', '可以查看博文'),), 'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
    ]
