# Generated by Django 2.0.3 on 2018-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180731_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', '私有'), ('published', '公开')], default='draft', max_length=10, verbose_name='编辑状态'),
        ),
    ]
