# Generated by Django 2.0.3 on 2018-08-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180804_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='博文封面url'),
        ),
    ]
