# Generated by Django 2.0.3 on 2018-08-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180801_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否轮播'),
        ),
    ]
