# Generated by Django 2.0.3 on 2018-05-14 15:46

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180514_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Post', verbose_name='上一篇博文'),
        ),
    ]
