# Generated by Django 2.0.3 on 2018-08-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180804_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comment',
            field=models.BooleanField(default=True, verbose_name='允许发表评论'),
        ),
    ]
