# Generated by Django 2.0.3 on 2018-08-08 23:04

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_allow_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='blog/blog_cover/default.jpg', max_length=200, upload_to='blog/blog_cover/', verbose_name='博文封面'),
        ),
    ]
