# Generated by Django 2.0.3 on 2018-05-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180514_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('post', '博文'), ('notification', '公告')], default='post', max_length=13, verbose_name='博客类型'),
        ),
    ]
