# Generated by Django 2.0.3 on 2018-08-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.FloatField(default=0, verbose_name='博文价格'),
        ),
    ]
