# Generated by Django 2.0.3 on 2018-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180514_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否是轮播图'),
        ),
    ]
