# Generated by Django 2.0.3 on 2018-08-02 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='黑名单ip')),
                ('desc', models.CharField(blank=True, help_text='300字以内', max_length=300, null=True, verbose_name='原因')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '站点黑名单',
                'verbose_name_plural': '站点黑名单',
            },
        ),
        migrations.CreateModel(
            name='BlogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ')),
                ('github', models.URLField(default='', verbose_name='博主GitHub主页地址')),
                ('gitee', models.URLField(default='', verbose_name='博主GitEE主页地址')),
                ('recommend_posts', models.ManyToManyField(to='blog.Post', verbose_name='博主推荐的博文')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博主')),
            ],
            options={
                'verbose_name': '博主个人信息',
                'verbose_name_plural': '博主个人信息',
            },
        ),
        migrations.CreateModel(
            name='FriendshipLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息')),
                ('has_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('published_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '站内通知',
                'verbose_name_plural': '站内通知',
            },
        ),
        migrations.CreateModel(
            name='NotificationUnReadCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_unread', models.PositiveIntegerField(default=0, verbose_name='未读数量')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '未读消息计数器',
                'verbose_name_plural': '未读消息计数器',
            },
        ),
    ]
