# Generated by Django 2.0.3 on 2018-04-24 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationUnReadCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_unread', models.PositiveIntegerField(default=0, verbose_name='未读数量')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='消息人')),
            ],
            options={
                'verbose_name': '未读消息计数器',
                'verbose_name_plural': '未读消息计数器',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='n_unread',
        ),
    ]
