# Generated by Django 2.0.3 on 2018-07-30 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(verbose_name='黑名单ip')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
            ],
            options={
                'verbose_name': '站点黑名单',
                'verbose_name_plural': '站点黑名单',
            },
        ),
    ]
