# Generated by Django 2.0.3 on 2018-05-14 18:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_auto_20180514_1546'),
        ('oper', '0002_blogownerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息')),
                ('published_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '博客公告',
                'verbose_name_plural': '博客公告',
            },
        ),
        migrations.CreateModel(
            name='BlogOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qq', models.CharField(max_length=15, verbose_name='QQ')),
                ('github', models.URLField(verbose_name='博主GitHub地址')),
                ('recommend_posts', models.ManyToManyField(to='blog.Post', verbose_name='博主推荐的博文')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博主')),
            ],
            options={
                'verbose_name': '博主个人信息',
                'verbose_name_plural': '博主个人信息',
            },
        ),
        migrations.RemoveField(
            model_name='blogownerinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogOwnerInfo',
        ),
    ]
