# Generated by Django 2.0.3 on 2018-07-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0002_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='desc',
            field=models.CharField(blank=True, help_text='300字以内', max_length=300, null=True, verbose_name='原因'),
        ),
    ]
