# Generated by Django 2.0.3 on 2018-05-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0003_auto_20180514_1843'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogNotification',
        ),
    ]
