# Generated by Django 2.0.3 on 2018-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0004_delete_blognotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogowner',
            name='gitee',
            field=models.URLField(default='', verbose_name='博主GitEE主页地址'),
        ),
        migrations.AlterField(
            model_name='blogowner',
            name='github',
            field=models.URLField(default='', verbose_name='博主GitHub主页地址'),
        ),
    ]
