# Generated by Django 2.0.3 on 2018-05-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0005_auto_20180514_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendshipLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('url', models.URLField(verbose_name='地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
