# Generated by Django 2.0.3 on 2018-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0006_friendshiplinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='轮播标题')),
                ('image', models.ImageField(upload_to='banner/%Y/%m/', verbose_name='轮播图')),
                ('url', models.URLField(blank=True, null=True, verbose_name='访问地址')),
            ],
            options={
                'verbose_name': '博客轮播图',
                'verbose_name_plural': '博客轮播图',
            },
        ),
    ]
