# Generated by Django 2.0.3 on 2018-05-15 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oper', '0007_blogbanner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogBanner',
        ),
    ]
